name: "Integration Testing"

on: [push]

jobs:
  dispatch-events:
    if: github.event.repository.full_name == 'github/codeql-action'
    runs-on: ubuntu-latest
    steps:
    - name: Send repository dispatch events
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.CODEQL_TESTING_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/Anthophila/amazon-cognito-js-copy/dispatches \
          -d '{"event_type":"codeql-integration","client_payload": {"sha": "${{ github.sha }}"}}'

        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.CODEQL_TESTING_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/Anthophila/electron-test-action/dispatches \
          -d '{"event_type":"codeql-integration","client_payload": {"sha": "${{ github.sha }}"}}'
