name: Update release branch
on:
  schedule:
    - cron: 0 9 * * 1
  repository_dispatch:
    # Example of how to trigger this:
    # curl -H "Authorization: Bearer <token>" -X POST https://api.github.com/repos/github/codeql-action/dispatches -d '{"event_type":"update-release-branch"}'
    # Replace <token> with a personal access token from this page: https://github.com/settings/tokens
    types: [update-release-branch]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'github/codeql-action' }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Need full history so we calculate diffs
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub==1.51 requests

    - name: Update git config
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Update release branch
      run: python .github/update-release-branch.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
